nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Link']
        allow_methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': ~
